version: '3.5'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    container_name: frontend-react

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./backend:/usr/src/app
    container_name: backend-django
    command: ["sh", "start.sh"]
  
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5400:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
