version: '3.7'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5400:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-volume:/var/lib/postgresql/data
    
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    # environment:
    #   - DB_NAME=testdb
    #   - DB_PASSWORD=postgres
    #   - DB_USER=postgres
    #   - DB_HOST=db
    #   - DB_PORT=5432
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: ["sh", "start.sh"]

volumes:
  db-volume:
